name: rc_router
description: A simple but powerful Flutter router.
version: 1.0.0
homepage: https://rushio-consulting.fr

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  pedantic: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
