name: On master

on:
  push:
    branches:
      - master
    paths:
      - '*.dart'
      - '*.g.dart'

jobs:
  flutter:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:stable

    steps:
    - uses: actions/checkout@v1
    - run: sudo chown -R cirrus:cirrus ./ /github/home/
    - name: Flutter pub get
      run: flutter packages get
    - name: Flutter test
      run: flutter test --coverage
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./coverage.yml

